# Generated by Django 2.2.1 on 2019-06-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=None, verbose_name='Identificador'),
        ),
    ]
