# Generated by Django 2.2.1 on 2019-06-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
    ]
