# Generated by Django 2.2.1 on 2019-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=None, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
