# Generated by Django 2.2.1 on 2019-06-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador (slug)'),
        ),
    ]
